### ISSUE TITLE
Switch to python?

### ISSUE THREAD

**Issue by skylar-kantor** [JamesEConnor/NanoGeno2017#4]
Since we now have a working version of this in Python, is there any point in keeping to Java files? Or would you like to try and make a Java version of this, @JamesEConnor

**Comment by skylar-kantor** [comment]
Additionally, should we call this point V1.0, since we have a generator that more or less works?

**Comment by JamesEConnor** [comment]
Yeah, I'll convert it to Java tomorrow. It should be v1.0.

**Comment by skylar-kantor** [comment]
You might have some trouble with the list. I couldn't figure out how to put elements in specific placeccs without another ArrayList

**Comment by skylar-kantor** [comment]
Made a forked version with the python rewrite. It makes sentences that make some amount of sense
