### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by skylar-kantor** [JamesEConnor/NanoGeno2017#6]
1//12/17

Alex Kantor

When I try to generate more than 6 sentences, it appears that the program enters an infinite loop

**Comment by skylar-kantor** [comment]
Example:

How many sentences would you like to generate? 10
...It aerodynamically ripes the trustworthy abolition 
...You congenitally flounder the rove-over jellies 
...You concentrically jaculated the crinkly increasers 
...You heartlessly orphan the some wollastonite 
...She gutturally oversews the untanned reintegrations 
...He mellifluously practices the lenient helve 
...We callously clam the hippodromic tranquillity 
...She sinistrally truckles the freewheeling protostele 
...It duskily retails the desirous ecus 
...I will be misleadingly interring the aware exhalants 
...You will be prayerfully eluding the raped restaurateurs 
...We good-naturedly constellate the assentient alums 
...They musically hydrolysed the nubby thujas 
...She invariably outjockeys the front Koblenz 
...They squashily sieged the fervent overstatement 
...We will be clannishly liberating the self-raised authenticator 
...He taxably corrivals the trad philanthropists 
...They imperiously eat the decomposable variscite 
...We will be assumingly decarburizing the proximal diagnosis 
..

**Comment by JamesEConnor** [comment]
Is it because *i += 1 *is indented at line 119?

**Comment by skylar-kantor** [comment]
It only occurs with the delay I added (See my forked version)

**Comment by skylar-kantor** [comment]
And that indentation actually keeps it from not displaying enough valid sentences

**Comment by JamesEConnor** [comment]
You're using `i` in the `for` loop as well as the `while` loop. This makes `i` always equal to the number of words in the sentence. Try renaming `i` in the `for` loop.

**Comment by skylar-kantor** [comment]
Ahhh, that makes sense. Should have caught that.
